POST http://localhost:5001/api/auth/login

{"username":"admin2","password":"secret"}

###

GET http://localhost:5001/api/auth/me

###

GET http://localhost:5001/api/user

###









POST http://localhost:3000/graphql HTTP/1.1
content-type: application/json

{
    "query": "{ getAll { nome } }"
}

###



POST http://localhost:3000/graphql HTTP/1.1
content-type: application/json

{
    "query": "{ getById (id:\"xxx\") { nome } }"
}

###


POST http://localhost:3000/graphql HTTP/1.1
content-type: application/json

{
    "query": "mutation { store (user:{nome:\"ivano\"}) { id nome } }"
}

###









// store(Request $request) salva un record
POST http://localhost:8063/api/segreteria HTTP/1.1
content-type: application/json

{
    "username": "pippo3",
    "email": "pippo3@gmail.com",
    "password": "zigomo"
}

###

// elimina uno specifico record
DELETE http://localhost:8063/api/segreteria/4eb0fd84-94dc-11e8-8be1-0242ac180004 HTTP/1.1




###



// AVVISO

// index: preleva tutti i record
GET http://localhost:8063/api/avviso HTTP/1.1

###

// store: salva un record
POST http://localhost:8063/api/avviso HTTP/1.1
content-type: application/json

{
    "title":"altro titolo",
    "description":"ertino",
    "start_date":"2018-08-01",
    "end_date":"2018-09-01 11:31:00"
}

###

// update: modifica un record esistente
PATCH http://localhost:8063/api/avviso/32c2bf76-9631-11e8-96dc-0242ac180004 HTTP/1.1
content-type: application/json

{
    "title": "pippo4",
    "description": "pippo4@gmail.com",
    "start_date": "2018-08-01",
    "end_date": "2018-08-30 10:25:40"
}

###

// elimina uno specifico record
DELETE http://localhost:8063/api/avviso/32c2bf76-9631-11e8-96dc-0242ac180004 HTTP/1.1


###


GET http://localhost:8063/api/candidato/50e9c98a-9c95-11e8-8b0b-0242ac3f0002 HTTP/1.1